apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.demo.yml convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mender-inventory
  name: mender-inventory
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mender-inventory
    spec:
      containers:
      - args:
        - server
        - --automigrate
        image: mendersoftware/inventory
        name: mender-inventory
        resources: {}
      restartPolicy: Always
status: {}
