apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.demo.yml convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mender-gui
  name: mender-gui
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mender-gui
    spec:
      containers:
      - env:
        - name: DEMO
          value: "true"
        image: mendersoftware/gui
        name: mender-gui
        resources: {}
      restartPolicy: Always
status: {}
