apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.demo.yml convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mender-conductor
  name: mender-conductor
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mender-conductor
    spec:
      containers:
      - env:
        - name: CONFIG_PROP
          value: config.properties
        image: mendersoftware/mender-conductor:master
        name: mender-conductor
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /app/config
          name: mender-conductor-claim0
      restartPolicy: Always
      volumes:
      - name: mender-conductor-claim0
        persistentVolumeClaim:
          claimName: mender-conductor-claim0
status: {}
