apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.demo.yml convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mender-useradm
  name: mender-useradm
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mender-useradm
    spec:
      containers:
      - args:
        - server
        - --automigrate
        image: mendersoftware/useradm
        name: mender-useradm
        resources: {}
        volumeMounts:
        - mountPath: /etc/useradm/rsa/private.pem
          name: mender-useradm-claim0
      restartPolicy: Always
      volumes:
      - name: mender-useradm-claim0
        persistentVolumeClaim:
          claimName: mender-useradm-claim0
status: {}
