apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.demo.yml convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: storage-proxy
  name: storage-proxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: storage-proxy
    spec:
      containers:
      - env:
        - name: DOWNLOAD_SPEED
          value: 3m
        - name: MAX_CONNECTIONS
          value: "30"
        image: openresty/openresty:1.13.6.2-0-alpine
        name: storage-proxy
        ports:
        - containerPort: 9000
        resources: {}
        volumeMounts:
        - mountPath: /var/www/storage-proxy/cert/cert.crt
          name: storage-proxy-claim0
        - mountPath: /var/www/storage-proxy/cert/private.key
          name: storage-proxy-claim1
      restartPolicy: Always
      volumes:
      - name: storage-proxy-claim0
        persistentVolumeClaim:
          claimName: storage-proxy-claim0
      - name: storage-proxy-claim1
        persistentVolumeClaim:
          claimName: storage-proxy-claim1
status: {}
